apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: nginx
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            command:
            - sh
            - -c
            - echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

